name: Debug ESPN League

on:
  workflow_dispatch: {}

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Debug League Connection
        env:
          LEAGUE_ID: ${{ secrets.LEAGUE_ID }}
          SEASON_ID: ${{ secrets.SEASON_ID }}
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          SWID: ${{ secrets.SWID }}
        run: python debug_league.py
